#!/usr/bin/env bash
# Generates dev/ibmmq/20-spb-queues.mqsc (queues and permissions) from IBMMQ_* variables in the project root .env file.
# Usage: run from the repo root (or from dev/ibmmq/):
#   bash dev/ibmmq/gen-setup-spb-queues.sh
# Requires: jq. The generated file is mounted by docker-compose and applied automatically on QM1 startup.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Repo root (where .env and .env.example live)
if [[ -f "$SCRIPT_DIR/../../.env" ]]; then
  ENV_FILE="$SCRIPT_DIR/../../.env"
else
  ENV_FILE="$SCRIPT_DIR/../.env"
fi

if [[ ! -f "$ENV_FILE" ]]; then
  # Try to bootstrap from .env.example in the repo root
  if [[ -f "$SCRIPT_DIR/../../.env.example" ]]; then
    echo ".env not found. Bootstrapping from .env.example..."
    cp "$SCRIPT_DIR/../../.env.example" "$SCRIPT_DIR/../../.env"
    ENV_FILE="$SCRIPT_DIR/../../.env"
  else
    echo ".env file not found (looked for $ENV_FILE) and .env.example is also missing. Create it and define the IBMMQ_* variables." >&2
    exit 1
  fi
fi

if ! command -v jq &>/dev/null; then
  echo "jq is required. Install with: brew install jq (macOS) or apt-get install jq (Linux)." >&2
  exit 1
fi

# Load env variables from .env
set -a
# shellcheck disable=SC1090
source "$ENV_FILE"
set +a

: "${IBMMQ_HOST:?IBMMQ_HOST is required in .env}"
: "${IBMMQ_PORT:?IBMMQ_PORT is required in .env}"
: "${IBMMQ_CHANNEL:?IBMMQ_CHANNEL is required in .env}"
: "${IBMMQ_USER:?IBMMQ_USER is required in .env}"
: "${IBMMQ_PASSWORD:?IBMMQ_PASSWORD is required in .env}"
: "${IBMMQ_QMGR_NAME:?IBMMQ_QMGR_NAME is required in .env}"
: "${IBMMQ_QUEUES:?IBMMQ_QUEUES is required in .env (comma-separated list of queue names)}"

# Build JSON config from individual IBMMQ_* variables
IFS=',' read -ra QUEUE_NAMES <<< "$IBMMQ_QUEUES"

QUEUES_JSON=""
for q in "${QUEUE_NAMES[@]}"; do
  q_trimmed=$(echo "$q" | xargs)
  [[ -z "$q_trimmed" ]] && continue
  if [[ -n "$QUEUES_JSON" ]]; then
    QUEUES_JSON+=","
  fi
  QUEUES_JSON+="{\"queue_name\": \"${q_trimmed}\"}"
done

RAW=$(cat <<EOF
[
  {
    "host": "${IBMMQ_HOST}",
    "port": ${IBMMQ_PORT},
    "channel": "${IBMMQ_CHANNEL}",
    "user": "${IBMMQ_USER}",
    "password": "${IBMMQ_PASSWORD}",
    "queue_manager": {
      "name": "${IBMMQ_QMGR_NAME}",
      "queues": [${QUEUES_JSON}]
    }
  }
]
EOF
)

# Queue list: queue_manager.queues[].queue_name from all hosts
QUEUES=($(echo "$RAW" | jq -r '.[].queue_manager.queues[]? | .queue_name // empty' 2>/dev/null | sort -u))
# Always include the stage queue (consumed by the StageServer; must not be listed in queues for the IBMMQServer)
STAGE_QUEUE="QL.STG.NOTIFY.01"
HAS_STAGE=false
for q in "${QUEUES[@]}"; do
  [[ "$q" == "$STAGE_QUEUE" ]] && HAS_STAGE=true
done
if [[ "$HAS_STAGE" != "true" ]]; then
  QUEUES+=("$STAGE_QUEUE")
fi

# Optional queues for SPB flow (generic report/support)
EXTRA_QUEUES=("QL.SUP.LOCAL.01" "QL.REP.LOCAL.01")
for eq in "${EXTRA_QUEUES[@]}"; do
  if [[ " ${QUEUES[*]} " != *" $eq "* ]]; then
    QUEUES+=("$eq")
  fi
done

# Outbound queues: the application sends to QR.{TYPE}.{SENDER}.{RECIPIENT}.{domain}
# Derived from QL.*: for each QL.{type}.{sender}.{recipient}.{domain} (inbound Bacen→participant),
# we create QR.{type}.{recipient}.{sender}.{domain} (outbound participant→Bacen) so MQOPEN does not fail [2085]
OUTBOUND_QUEUES=()
for q in "${QUEUES[@]}"; do
  if [[ "$q" =~ ^QL\.(REQ|RSP|REP|SUP)\.([0-9]{8})\.([0-9]{8})\.([0-9]{2})$ ]]; then
    qr="QR.${BASH_REMATCH[1]}.${BASH_REMATCH[3]}.${BASH_REMATCH[2]}.${BASH_REMATCH[4]}"
    if [[ " ${OUTBOUND_QUEUES[*]} " != *" $qr "* ]]; then
      OUTBOUND_QUEUES+=("$qr")
    fi
  fi
done

ALL_QUEUES=("${QUEUES[@]}" "${OUTBOUND_QUEUES[@]}")

OUT_FILE="$SCRIPT_DIR/20-spb-queues.mqsc"
{
  echo '* Queues and authorizations for the SPB app on localhost (dev)'
  echo '* Generated by dev/ibmmq/gen-setup-spb-queues.sh from .env (IBMMQ_* variables).'
  echo '* Channel DEV.APP.SVRCONN and user app already exist in the official IBM MQ Developer image.'
  echo '*'
  echo '* Convention: QL.{TYPE}.{SENDER}.{RECIPIENT}.NN = inbound; QR.* = outbound (application send).'
  echo '*   QL.STG.NOTIFY.01 is only consumed by the StageServer; do not include it in queue_manager.queues in .env.'
  echo '*'
  for q in "${QUEUES[@]}"; do
    echo "DEFINE QLOCAL($q) REPLACE"
  done
  if [[ ${#OUTBOUND_QUEUES[@]} -gt 0 ]]; then
    echo '*'
    echo '* Output queues (outbound): QR.{TYPE}.{participant}.{Bacen}.NN — derived from QL.* above'
    for q in "${OUTBOUND_QUEUES[@]}"; do
      echo "DEFINE QLOCAL($q) REPLACE"
    done
  fi
  echo '*'
  echo '* Permissions for user app on all queues'
  echo "SET AUTHREC OBJTYPE(QMGR) PRINCIPAL('app') AUTHADD(ALL)"
  for q in "${ALL_QUEUES[@]}"; do
    echo "SET AUTHREC PROFILE($q) OBJTYPE(QUEUE) PRINCIPAL('app') AUTHADD(ALL)"
  done
  echo 'REFRESH SECURITY (*)'
} > "$OUT_FILE"

echo "→ $OUT_FILE generated with ${#QUEUES[@]} inbound queues + ${#OUTBOUND_QUEUES[@]} outbound (${#ALL_QUEUES[@]} total)."
echo "→ It will be applied automatically on QM1 startup via docker-compose volume mount."